"""On-demand sampling of a finished case: arbitrary slice planes and
streamlines, generated by running `postProcess -func` against the saved
solution fields, then cached as JSON in the run dir."""
from __future__ import annotations

import json
import subprocess
import threading
from pathlib import Path

import numpy as np

from . import post
from .foamenv import OPENFOAM

# postProcess mutates system/ and postProcessing/ inside a case; serialize.
_LOCK = threading.Lock()

_SLICE_FO = """type            surfaces;
libs            (sampling);
writeControl    writeTime;
surfaceFormat   vtk;
formatOptions
{
    vtk
    {
        legacy      true;
        format      ascii;
    }
}
fields          (p U);
interpolationScheme cellPoint;
surfaces
{
    onDemandPlane
    {
        type        cuttingPlane;
        planeType   pointAndNormal;
        pointAndNormalDict
        {
            point   POINT;
            normal  NORMAL;
        }
        interpolate true;
    }
}
"""

_STREAM_FO = """type            streamLine;
libs            (fieldFunctionObjects);
writeControl    writeTime;
setFormat       vtk;
formatOptions { vtk { legacy true; format ascii; } }
U               U;
fields          (U);
direction       forward;
lifeTime        10000;
nSubCycle       5;
cloud           particleTracks;
seedSampleSet
{
    type        cloud;
    axis        xyz;
    points
    (
POINTS
    );
}
"""


def _run_postprocess(case: Path, func: str) -> None:
    cmd = (f'cd "{case}" && postProcess -func {func} -latestTime '
           f"> log.postProcess.{func} 2>&1")
    subprocess.run([OPENFOAM, "-c", cmd], capture_output=True, timeout=600)


def _latest_vtk(case: Path, func: str) -> Path | None:
    # surfaces FOs write under postProcessing/<func>/, set-writing FOs
    # (streamLine) under postProcessing/sets/<func>/.
    for base in (case / "postProcessing" / func,
                 case / "postProcessing" / "sets" / func):
        hits = sorted(base.rglob("*.vtk")) if base.exists() else []
        if hits:
            return hits[-1]
    return None


def _cached(cache: Path) -> dict | None:
    if cache.exists():
        try:
            return json.loads(cache.read_text())
        except (OSError, json.JSONDecodeError):
            return None
    return None


def slice_json(run_dir: Path, axis: str, pos: float, rho: float) -> dict:
    key = f"{pos:.6g}".replace("-", "m").replace(".", "p")
    cache = run_dir / f"viz_slice_{axis}_{key}.json"
    if (payload := _cached(cache)) is not None:
        return payload
    with _LOCK:
        if (payload := _cached(cache)) is not None:
            return payload
        case = run_dir / "case"
        if not case.exists():
            raise RuntimeError("case data unavailable (run compacted)")
        vec = {"x": "1 0 0", "y": "0 1 0", "z": "0 0 1"}[axis]
        point = {"x": f"({pos} 0 0)", "y": f"(0 {pos} 0)", "z": f"(0 0 {pos})"}[axis]
        (case / "system" / "onDemandSlice").write_text(
            _SLICE_FO.replace("POINT", point).replace("NORMAL", f"({vec})"))
        _run_postprocess(case, "onDemandSlice")
        vtk = _latest_vtk(case, "onDemandSlice")
        if vtk is None:
            raise RuntimeError(
                "slice produced no data (plane may be outside the domain); "
                f"see case/log.postProcess.onDemandSlice")
        try:
            points, tris, fields = post._load_tri_mesh(vtk)
            payload = post.plane_payload(points, tris, fields, rho)
        finally:
            # postProcessing/onDemandSlice would otherwise serve stale data
            # for the next position; the JSON cache is the durable copy.
            import shutil
            shutil.rmtree(case / "postProcessing" / "onDemandSlice",
                          ignore_errors=True)
        cache.write_text(json.dumps(payload))
        return payload


STREAM_DENSITY = {"low": 5, "med": 7, "high": 10}   # n -> n*n seed grid
STREAM_REGION = {"full": 1.15, "core": 0.6}          # span factor vs model bbox


def streamlines_json(run_dir: Path, model: dict, rho: float,
                     density: str = "med", region: str = "full") -> dict:
    cache = run_dir / f"viz_streamlines_{density}_{region}.json"
    if (payload := _cached(cache)) is not None:
        return payload
    with _LOCK:
        if (payload := _cached(cache)) is not None:
            return payload
        case = run_dir / "case"
        if not case.exists():
            raise RuntimeError("case data unavailable (run compacted)")
        (bx0, by0, bz0), (bx1, by1, bz1) = model["bbox_m"]
        L = bx1 - bx0
        # Seed rake: 7x7 grid upstream of the model, spanning 1.15x its
        # frontal extent so lines both hug and pass the body.
        n = STREAM_DENSITY[density]
        span = STREAM_REGION[region]
        # Small jitter keeps seeds off exact cell faces (y=0/z=0 planes),
        # where OpenFOAM's particle tracking stalls immediately.
        x = bx0 - 0.7 * L + 1.3e-4
        ys = np.linspace(by0, by1, n) * span + 1.1e-4
        zs = np.linspace(bz0, bz1, n) * span + 1.7e-4
        pts = "\n".join(f"        ({x:.6g} {y:.6g} {z:.6g})"
                        for y in ys for z in zs)
        (case / "system" / "onDemandStreamlines").write_text(
            _STREAM_FO.replace("POINTS", pts))
        _run_postprocess(case, "onDemandStreamlines")
        vtk = _latest_vtk(case, "onDemandStreamlines")
        if vtk is None:
            raise RuntimeError("streamline tracking produced no data; "
                               "see case/log.postProcess.onDemandStreamlines")
        try:
            points, tracks, fields = post.load_legacy_polylines(vtk)
        finally:
            import shutil
            shutil.rmtree(case / "postProcessing" / "sets" / "onDemandStreamlines",
                          ignore_errors=True)
        if "U" not in fields:
            raise RuntimeError("field U missing on streamline tracks")
        u_mag = np.linalg.norm(np.asarray(fields["U"]).reshape(len(points), -1),
                               axis=1)
        u_mag = np.nan_to_num(u_mag, nan=0.0, posinf=0.0, neginf=0.0)
        payload = {
            "positions": [round(float(v), 6) for v in points.ravel()],
            "lines": [[int(i) for i in t] for t in tracks],
            "fields": {"u_mag": [float(v) for v in u_mag]},
            "ranges": {"u_mag": [float(u_mag.min()), float(u_mag.max())]},
        }
        cache.write_text(json.dumps(payload))
        return payload
